### ISSUE TITLE
Multimedia & Codec Packages

### ISSUE THREAD

**Issue by matiasvlevi** [DO2-Momo/yarp#5]
# Multimedia & Codec Packages

This category of packages is for the multimedia drivers (sound, video, etc) and the various available codecs

## Things we need

* Sound driver [arch wiki - sound drivers](https://wiki.archlinux.org/title/sound_system)
* Bluetooth driver [arch wiki - bluetooth](https://wiki.archlinux.org/title/bluetooth)
* Video viewer (`vlc` or other)
* Codecs for niche files (`flac`, `mpv`, etc) [arch wiki - codecs](https://wiki.archlinux.org/title/Codecs_and_containers)

You can find package names by googling the name of the software, with `arch linux` at the end.
AUR Packages are not valid in our case

## Add packages to the repository

Append the package names in the `./packages/multimedia.x86_64` text file.

**Comment by Mizorio** [comment]
I just added multimedia packages
